### ISSUE TITLE
Frequency integer overflow on 32bit systems

### ISSUE THREAD

**Issue by formtapez** [hb9tf/spectre#10]
Hey, this is very cool project!

I use the collector with a HackRF on an older Raspberry Pi wich is 32-Bit.
Frequencies higher than 2,147483647 GHz are a problem with that used integer data types :-)

Kind regards
form

**Comment by finfinack** [comment]
Thanks! We didn't really update it recently but happy to include PRs. I'm actually surprised to hear that it even works with older Raspberry Pis as I assumed it would be too taxing on the USB port and CPU in particular with the bandwidth of the HackRF.

Re 32bit ints: Nice observation! In an attempt to unify things, I pushed https://github.com/hb9tf/spectre/commit/5f952b4db58e4a607c0d7153c4964e60b738bf30 which should uniformly use `uint` which I'm hoping is more performant than explicitly using `uint64` or `int64` on 32bit systems. No strong opinion though.

Let me know if that works for you. This should at least push the HackRF on a 32bit rPi to 4'294'967'296 Hz :)

**Comment by formtapez** [comment]
Hey, thanks for your quick response!
Unfortunately, 4,2 GHz is not enough for monitoring 5 GHz Wifi :-(

I did a quick and dirty conversation to int64, which performs okay on the Raspi1.

I pushed the changes here, but they now got a bit mixed up with your uint version...
https://github.com/formtapez/spectre/commit/acf459bbd4266f3ab68ef812beca0ba8bffbb672

**Comment by finfinack** [comment]
Ah heh, fair enough - I've expanded it to `uint64` now - that should be enough for the next couple SDRs :)

Let me know if https://github.com/hb9tf/spectre/commit/b63fa5a49d883778200dcd4dc77021a303571d07 works for you (I only did some cursory testing as I don't have an SDR handy without rummaging through stuff right now).

**Comment by formtapez** [comment]
Seems to work on the collector and server side, but the renderer now has a problem:
`F0107 12:07:48.276903 3778891 render.go:122] Unable to render image: unable to get sample count from DB: sql: converting argument $4 type: uint64 values with high bit set are not supported
exit status 1
`

**Comment by finfinack** [comment]
Sigh, this seems to be a limitation of the SQL library that I won't be able to do much about.

We're preparing a statement here: https://github.com/hb9tf/spectre/blob/b63fa5a49d883778200dcd4dc77021a303571d07/extraction/extraction.go#L145

And http://go-database-sql.org/surprises.html seems to indicate we shouldn't use `uint64`...

I'll rewrite this to use an `int64` which should work but is IMO a bit unfortunate because it allows negative numbers that don't make sense here. Oh well.

I'll update this again once I pushed that. I'll also dig  up the HackRF if I can find it quickly enough to avoid too many back and forths.

**Comment by finfinack** [comment]
https://github.com/hb9tf/spectre/commit/79c9e77854f4c2444722c4119fe6e4a81114c903 is yet another attempt (using `int64` everywhere instead of `uint64` now) but is not tested yet. Waiting for the necessary software to be compiled before I can test it :)

**Comment by finfinack** [comment]
Sigh, there is a signature verification mismatch that I honestly don't have the time to investigate just to test if it works now (and too cautious to bypass it). I'd appreciate if you could test it after all. Thank you!

**Comment by formtapez** [comment]
Great, i tested collector, server and renderer without any issues on the higher bands!
Thank you very much for your blazing fast response time :-)

**Comment by finfinack** [comment]
Awesome, thank you for reporting the issue and testing it!
